services:
  mysql:
    image: mysql:latest
    container_name: store_manage
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - TZ=Asia/Taipei
    ports:
      - 30420:3306
    volumes:
      - './../volumes/database/store_manage:/var/lib/mysql'
    networks:
      - store


networks:
  store:
    name: backend_store
    driver: bridge

