services:
  mysql:
    image: mysql:latest
    container_name: mysql-store
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - TZ=Asia/Taipei
    ports:
      - 30420:3306
    volumes:
      - ./../volumes/database/mysql:/var/lib/mysql
    networks:
      - store
  

networks:
  store:
    name: backend_store
    driver: bridge
